/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "909ee014fcea6828f9a610e6716145bc0b3ebf4a"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
