/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "2c36ee834ae04d036363cd3b8f3f33ec65d657f0-"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
